baseurl = "https://kroger-workshop.cfapps.io"
languageCode = "en-us"
title = "Cloud Foundry Workshop at Kroger"


theme="material-design"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "Rajesh Jain" # optional
copyright = "© 2015 Copyright Text"

[params]
  description = "Cloud Foundry Workshops" # optional
  twitter = "rjain15" # optional
  # headerCover = "images/headerCover.png" # optional
  # footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "UA-75133856-1" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional

